site_name: Chronicler
site_author: Jacob Hilker

nav:
  - Home: index.md

theme:
  name: material

plugins:
- social
- mkdocstrings:
    handlers:
      python:
        paths: [chronicler]  # search packages in the chronicler folder
